[project]
name = "kuanrongyang-github-io-1"
version = "0.1.0"
description = ""
authors = [
    {name = "KUAN RONG YANG",email = "kuanrong0108@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "numpy (<2.5)",
    "pandas (>=3.0.5,<4.0.0)",
    "matplotlib (>=3.11.1,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "plotly (>=7.0.0,<8.0.0)"
]

[tool.poetry]
packages = [{include = "kuanrongyang"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
